name: Build & Deploy Server

on:
  workflow_dispatch:

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Linux]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@f759ed7f8fcb5137cb70873ecf663aa8a1bd998b
        with:
          name: gcgd-social-server
          preset: ${{ matrix.platform }}
          debugMode: "false"
          projectDir: gcgd-social-server
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_KEY }}
          source: "tgcgd-social-server.zip"
          target: /home/${{ secrets.VPS_USERNAME }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gcgd-social-server
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
